### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by mi-hol**

### CODE REVIEW

**Comment by whoisdecoy** [comment]
This is not a typo!

**Comment by mi-hol** [comment]
> This is not a typo!

then the word "thiccness" should be in an English dictionary, right?

See for yourself
image

**Comment by whoisdecoy** [comment]
> > This is not a typo!
> 
> then the word "thiccness" should be in an English dictionary, right?

It is in the [dictionary](https://www.urbandictionary.com/define.php?term=Thiccness) 😉

**Comment by mi-hol** [comment]
> It is in the [dictionary](https://www.urbandictionary.com/define.php?term=Thiccness) 😉

github rules are asking for harassment free behavior.
https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#what-happens-if-someone-violates-githubs-policies

**Comment by BravoAlphaFox** [comment]
If you are using Urban Dictionary as a spelling reference...

**Comment by node-dojo** [comment]
if you're not down with the thiccness just say so

**Pull request closed without merging**
